spring:

  # mysql 配置
  datasource:
    url: jdbc:mysql://10.20.54.162:3306/ztb_workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://172.18.50.109:3306/ztb_workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xdcplus.com
#    password: 1q2w3e4r

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 2

#knife4j配置
knife4j:
  # 是否是生产模式
  production: false

#email:
#  enabled: true
#  host: 172.18.0.219
#  port: 25
#  ssl-enable: false
#  avoid-auth-enable: false
#  username: S0735
#  password: Suntech@2021
#  from:
#    name: epurchase
#    email: epurchase@suntech-power.com

email:
  enabled: true
  host: 172.16.0.18
  port: 25
  ssl-enable: false
  avoid-auth-enable: false
  username: S0735
  password: Suntech@2021
  from:
    name: epurchase
    email: epurchase@suntech-power.com






















