version: "3"

services:

  ztb-portal-sd:
    build:
      context: ""
      dockerfile: Dockerfile
    image: ztb-portal-sd
    container_name: ztb-portal-sd
    restart: always
#    ports:
#      - 8600:80
    expose:
      - 80
    networks:
      - ztb_net

networks:
  ztb_net:
    external: true
