version: "3"

services:
  ztb-portal:
    image: 10.20.54.143:8000/ztb-sd/ztb-portal:latest
    container_name: ztb-portal
    env_file:
      - conf/portal
    networks:
      - ztb_net

networks:
  ztb_net:
    external: true
